version: 2
updates:
  - package-ecosystem: docker
    directory: ssh-client/1
    schedule:
      interval: daily
    assignees:
      - alexsuter

  - package-ecosystem: pip
    directory: read-the-docs/2
    schedule:
      interval: daily
    assignees:
      - alexsuter
