pipeline {
  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '50'))
  }

  triggers {
    cron '@midnight'
  }

  stages {
    stage('build') {
      steps {
        script {
          def build = load 'build.groovy'
          build.build("ssh-client/1")
        }
      }
    }
  }
}
