pipeline {
  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '50'))
  }
  
  triggers {
    cron '@midnight'
  }

  stages {
    stage('build') {
      steps {
        script {
          sh 'wget https://build.nas.ivyteam.io/edirectory/edirectory.tar.gz -O /tmp/edirectory.tar.gz'
          sh 'tar -xvf /tmp/edirectory.tar.gz -C /tmp'
          sh 'docker load --input /tmp/edir920.tar'
          def name = "edirectory:9.2.0"
          def image = docker.image(name)
          docker.withRegistry('https://docker-registry.ivyteam.io', 'docker-registry.ivyteam.io') {
            if (env.BRANCH_NAME == 'master') {
              image.push()
            }
            sh "docker image rm ${name}"
          }     
        }
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
